#!/bin/bash

#Christian Wert
#Project 1
#File: alamode-fetch

while getopts ":n:f:d:" opt; do		#n:hostname   f:file   d:directory
	case $opt in
		n)
			hostname=$OPTARG
			haveHostname=true
			;;
		f)
			file=$OPTARG
			haveFile=true
			;;
		d)
			directory=$OPTARG
			haveDirectory=true
			;;
	esac
done

if [ "$haveHostname" = true ] && [ "$haveFile" = true ]; then
	echo "too many arguments provided ([-n hostname] and [-f filename] cannot both be given)"
	exit 1
fi

if [ "$haveHostname" != true ] && [ "$haveFile" != true ]; then
	echo "too few arguments provided (either [-n hostname] or [-f filename] must be given)"
	exit 2
fi

if [ "$haveDirectory" = true ]; then
	if [ ! -d "$directory" ]; then
		mkdir "$directory"
	fi
	outputDir="$directory""/"
else
	TMPFILE=`mktemp -d`
	outputDir="$TMPFILE""/"
	echo "$TMPFILE"
fi

if [ "$haveFile" = true ]; then
	while read line
	do
		echo $line
		hostname=$line
		ssh -n $hostname "hostname;
		echo '=================='
		echo 'Users Currently Logged In:';
		w -h | wc -l;
		echo 'Processes in each state:';
		top -b -n 1 | grep Tasks; 
		echo 'Average load last 1 minute:';
		cat /proc/loadavg | tr -s [[:space:]] \\\n | head -1;
		echo 'Average load last 5 minutes:';
		cat /proc/loadavg | tr -s [[:space:]] \\\n | head -2 | tail -1;
		echo 'Average load last 15 minutes:';
		cat /proc/loadavg | tr -s [[:space:]] \\\n | head -3 | tail -1;
		" > "$outputDir""${hostname}"
	done < $file
else
	ssh $hostname "hostname;
	echo '=================='
	echo 'Users Currently Logged In:';
	w -h | wc -l;
	echo 'Processes in each state:';
	top -b -n 1 | grep Tasks; 
	echo 'Average load last 1 minute:';
	cat /proc/loadavg | tr -s [[:space:]] \\\n | head -1;
	echo 'Average load last 5 minutes:';
	cat /proc/loadavg | tr -s [[:space:]] \\\n | head -2 | tail -1;
	echo 'Average load last 15 minutes:';
	cat /proc/loadavg | tr -s [[:space:]] \\\n | head -3 | tail -1;
	" > "$outputDir""${hostname}"
fi

