#!/bin/bash

#Christian Wert
#Project 1
#File: alamode-publish

read directory	#get directory path from STDIN (echoed in alamode-fetch)

while getopts ":s:d:" opt; do
	case $opt in
		s)
			sourceDirectory=$OPTARG	 #specifies the directory to look in for the hostfiles containing the data saved by alamode-fetch
			haveSourceDirectory=true
			;;
		d)
			htmlDirectory=$OPTARG	#specifies the directory where the website should be written
			havehtmlDirectory=true
			;;
	esac
done


#set up html
htmlString="<!DOCTYPE html>	
<html>
<head>
<meta charset='UTF-8'> 
<style>
table{border:1px solid black;border-collapse: collapse; width:75%;}
th,td{border:1px solid black; text-align:center;}
</style>
<title>Alamode Lab Status</title>
</head>
<body>
<table>
<tr><th>Hostname</th><th>Users Logged In</th><th>Total Processes</th><th>Running Processes</th><th>Sleeping Processes</th><th>Stopped Processes</th><th>Zombie Processes</th><th>Load Avg Last min</th><th>Load Avg Last 5 min</th><th>Load Avg Last 15 min</th></tr>"

#cd $directory	#change to directory retrieved from STDIN
for f in $directory/*; do
	array=()
	while read line; do
		array+=("$line")
	done < $f

	if [ $(echo "${array[9]} < .1" | bc) -eq 1 ]; then
		fifteen="green"
	elif [ $(echo "${array[9]} > .7" | bc) -eq 1 ]; then
		fifteen="red"
	else
		fifteen="yellow"
	fi
	htmlString=$htmlString"<tr style='background-color:$fifteen'><td>${array[0]}</td><td>${array[1]}</td><td>${array[2]}</td><td>${array[3]}</td><td>${array[4]}</td><td>${array[5]}</td><td>${array[6]}</td><td>${array[7]}</td><td>${array[8]}</td><td>${array[9]}</td></tr>"
done


htmlString=$htmlString"</table></body></html>" #end html
echo $htmlString > "boom.html"
